config/routes.rb
Rails.application.routes.draw do
  root to: 'application#index'
  resources :movie_categories
  resources :actor_movies
  resources :movies
  resources :addresses
  resources :categories
  resources :actors
  resources :directors

  get '/persons/new', to: 'persons#new'
  get '/persons/show', to: 'persons#show'
  post '/persons/create', to: 'persons#create'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/movie_category.rb
class MovieCategory < ApplicationRecord
  belongs_to :movie
  belongs_to :category
end

app/controllers/movie_categories_controller.rb
class MovieCategoriesController < ApplicationController
  before_action :set_movie_category, only: [:show, :edit, :update, :destroy]

  # GET /movie_categories
  # GET /movie_categories.json
  def index
    @movie_categories = MovieCategory.all
  end

  # GET /movie_categories/1
  # GET /movie_categories/1.json
  def show
  end

  # GET /movie_categories/new
  def new
    @movie_category = MovieCategory.new
  end

  # GET /movie_categories/1/edit
  def edit
  end

  # POST /movie_categories
  # POST /movie_categories.json
  def create
    @movie_category = MovieCategory.new(movie_category_params)

    respond_to do |format|
      if @movie_category.save
        format.html { redirect_to @movie_category, notice: 'Movie category was successfully created.' }
        format.json { render :show, status: :created, location: @movie_category }
      else
        format.html { render :new }
        format.json { render json: @movie_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movie_categories/1
  # PATCH/PUT /movie_categories/1.json
  def update
    respond_to do |format|
      if @movie_category.update(movie_category_params)
        format.html { redirect_to @movie_category, notice: 'Movie category was successfully updated.' }
        format.json { render :show, status: :ok, location: @movie_category }
      else
        format.html { render :edit }
        format.json { render json: @movie_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movie_categories/1
  # DELETE /movie_categories/1.json
  def destroy
    @movie_category.destroy
    respond_to do |format|
      format.html { redirect_to movie_categories_url, notice: 'Movie category was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie_category
      @movie_category = MovieCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def movie_category_params
      params.fetch(:movie_category, {})
    end
end

app/helpers/movie_categories_helper.rb
module MovieCategoriesHelper
end

app/views/movie_categories/_form.html.erb
<%= form_with(model: movie_category, local: true) do |form| %>
  <% if movie_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(movie_category.errors.count, "error") %> prohibited this movie_category from being saved:</h2>

      <ul>
      <% movie_category.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/movie_categories/edit.html.erb
<h1>Editing Movie Category</h1>

<%= render 'form', movie_category: @movie_category %>

<%= link_to 'Show', @movie_category %> |
<%= link_to 'Back', movie_categories_path %>

app/views/movie_categories/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Movie Categories</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @movie_categories.each do |movie_category| %>
      <tr>
        <td><%= link_to 'Show', movie_category %></td>
        <td><%= link_to 'Edit', edit_movie_category_path(movie_category) %></td>
        <td><%= link_to 'Destroy', movie_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Movie Category', new_movie_category_path %>

app/views/movie_categories/new.html.erb
<h1>New Movie Category</h1>

<%= render 'form', movie_category: @movie_category %>

<%= link_to 'Back', movie_categories_path %>

app/views/movie_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_movie_category_path(@movie_category) %> |
<%= link_to 'Back', movie_categories_path %>